stages:
- main

check:clippy:
  stage: main
  script:
  - cargo clippy --color always --workspace --all-features --all-targets --no-deps -- -Dwarnings
  allow_failure: true

check:fmt:
  stage: main
  script:
  - cargo fmt -- --check --color always
  allow_failure: true

build:
  stage: main
  script:
  # Report on the used Rust version
  - rustc --version

  # Build the project
  - cargo build -vv --color always

test:
  stage: main
  needs:
  - build
  script:
  - RUST_BACKTRACE=1 cargo test --color always --workspace --no-fail-fast
